apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "shouldwork"
  description: "asdasd"
  annotations:
    github.com/project-slug: outesting/shouldwork
    backstage.io/techdocs-ref: dir:.
spec:
  type: repository
  lifecycle: experimental
  owner: "group:default/spiderman"
